[package]
name = "day-12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-utils = { version = "0.1.0", path = "../aoc-utils" }
cached = "0.46.1"
itertools = "0.12.0"
