[package]
name = "day-17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-utils = { version = "0.1.0", path = "../aoc-utils" }
colorous = "1.0.12"
priority-queue = "1.3.2"
yansi = "0.5.1"
